### PR TITLE
Scamme systemet

### PR DESCRIPTION
**Pull request by Vitiation**

### CODE REVIEW

**Comment by christofferbuen** [comment]
LOOKS GOOD TO MEW!§!!

**Review by MartinRovang — CHANGES_REQUESTED** [review]
Update version and solve conflig, other than that, LGTM

**Review by christofferbuen — APPROVED** [review]
cool

**Review by MartinRovang — CHANGES_REQUESTED** [review]
Bump patch version and we're GTG

**Review by christofferbuen — APPROVED** [review]

**Review by MartinRovang — APPROVED** [review]
LGTM

**Pull request merged**
