### PR TITLE
Add some BDSM

### PR DESCRIPTION
**Pull request by DanRJ**

### CODE REVIEW

**Comment by DanRJ** [comment]
APPROVE IT FUCKER

**Comment by DanRJ** [comment]
> APPROVE IT FUCKER

GOOD REPLY!

**Comment by christofferbuen** [comment]
https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webp

**Review by christofferbuen — APPROVED** [review]
https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webphttps://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExajNjenBnNWd1dnFyNHNseWJvZjB2dWhrbW16djhzMDMxb3U4ZXFzMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NytMLKyiaIh6VH9SPm/giphy.webp

**Comment by DanRJ** [comment]
> Alt Text

VERY GOOD

**Review by MartinRovang — APPROVED** [review]
Alt Text

**Pull request merged**
